# Generated by Django 2.2.1 on 2019-08-02 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TM_PWD_TOKEN',
            fields=[
                ('token_id', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TM_PWD_TOKEN',
            },
        ),
    ]
