# Generated by Django 2.2.1 on 2019-08-01 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PWD_RESET_TOKEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.ForeignKey(db_column='dept_org_id', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pwd_reset_token_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PWD_RESET_TOKEN',
            },
        ),
    ]
