# Generated by Django 2.2.1 on 2019-08-01 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwd_reset_token',
            name='id',
        ),
        migrations.AlterField(
            model_name='pwd_reset_token',
            name='email',
            field=models.ForeignKey(db_column='email_id', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pwd_reset_token_email', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pwd_reset_token',
            name='token_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
