# Generated by Django 2.2.1 on 2019-08-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TM_USER_TOKEN',
            fields=[
                ('token_id', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TM_USER_TOKEN',
            },
        ),
    ]
