# Generated by Django 2.2.1 on 2019-08-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_auto_20190801_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwd_reset_token',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
