# Generated by Django 2.2.1 on 2019-07-30 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TM_DEPT',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('dept_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=15)),
                ('dept_desc', models.CharField(max_length=30)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_dept_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TM_DEPT',
            },
        ),
        migrations.CreateModel(
            name='TM_ORG',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('org_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=30)),
                ('org_address', models.CharField(max_length=40)),
                ('org_ext', models.BooleanField()),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_org_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_org_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TM_ORG',
            },
        ),
        migrations.CreateModel(
            name='TM_POST',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('post_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('post_name', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_post_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_post_modified', to=settings.AUTH_USER_MODEL)),
                ('post_dept_id', models.ForeignKey(db_column='post_dept_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_DEPT')),
                ('post_org_id', models.ForeignKey(db_column='post_org_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_ORG')),
            ],
            options={
                'db_table': 'TM_POST',
            },
        ),
        migrations.CreateModel(
            name='TM_RESPONSIBILITY',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('resp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resp_name', models.CharField(max_length=15)),
                ('resp_desc', models.CharField(max_length=30)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_responsibility_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_responsibility_modified', to=settings.AUTH_USER_MODEL)),
                ('resp_org_id', models.ForeignKey(db_column='resp_org_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_ORG')),
            ],
            options={
                'db_table': 'TM_RESPONSIBILITY',
            },
        ),
        migrations.CreateModel(
            name='TM_USER',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user_addr1', models.CharField(max_length=20)),
                ('user_mobile_num', models.BigIntegerField()),
                ('user_email_id', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_user_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_user_modified', to=settings.AUTH_USER_MODEL)),
                ('password', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tm_user_password', to=settings.AUTH_USER_MODEL)),
                ('user_dept_id', models.ForeignKey(db_column='user_dept_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_DEPT')),
            ],
            options={
                'db_table': 'TM_USER',
            },
        ),
        migrations.CreateModel(
            name='TM_USER_GROUP',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('group_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=20)),
                ('group_desc', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_user_group_created', to=settings.AUTH_USER_MODEL)),
                ('group_dept_id', models.ForeignKey(db_column='group_dept_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_DEPT')),
                ('group_org_id', models.ForeignKey(db_column='group_org_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_ORG')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_user_group_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TM_USER_GROUP',
            },
        ),
        migrations.CreateModel(
            name='TM_USER_CONTACT',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user_cont_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_cont_addr2', models.CharField(max_length=20)),
                ('user_cont_addr3', models.CharField(max_length=20)),
                ('user_cont_city', models.CharField(max_length=20)),
                ('user_cont_state', models.CharField(max_length=20)),
                ('user_cont_country_code', models.CharField(max_length=5)),
                ('user_cont_zip_code', models.BigIntegerField()),
                ('user_mobile_num2', models.BigIntegerField()),
                ('user_email_id2', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_user_contact_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_user_contact_modified', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(db_column='user_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_USER')),
            ],
            options={
                'db_table': 'TM_USER_CONTACT',
            },
        ),
        migrations.AddField(
            model_name='tm_user',
            name='user_group_id',
            field=models.ForeignKey(db_column='user_group_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_USER_GROUP'),
        ),
        migrations.AddField(
            model_name='tm_user',
            name='user_org_id',
            field=models.ForeignKey(db_column='user_org_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_ORG'),
        ),
        migrations.AddField(
            model_name='tm_user',
            name='user_post_id',
            field=models.ForeignKey(db_column='user_post_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_POST'),
        ),
        migrations.AddField(
            model_name='tm_user',
            name='user_resp_id',
            field=models.ForeignKey(db_column='user_resp_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_RESPONSIBILITY'),
        ),
        migrations.AddField(
            model_name='tm_user',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tm_user_username', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TM_ORG_CONTACT',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('org_cont_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('org_cont_addr2', models.CharField(max_length=20)),
                ('org_cont_addr3', models.CharField(max_length=20)),
                ('org_cont_city', models.CharField(max_length=20)),
                ('org_cont_state', models.CharField(max_length=20)),
                ('org_cont_country_code', models.CharField(max_length=5)),
                ('org_cont_zip_code', models.BigIntegerField()),
                ('org_cont_phone', models.BigIntegerField()),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_org_contact_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_org_contact_modified', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(db_column='org_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_ORG')),
            ],
            options={
                'db_table': 'TM_ORG_CONTACT',
            },
        ),
        migrations.AddField(
            model_name='tm_dept',
            name='dept_org_id',
            field=models.ForeignKey(db_column='dept_org_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_ORG'),
        ),
        migrations.AddField(
            model_name='tm_dept',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_dept_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TM_ACCESS_VIEWS',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('view_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('view_name', models.CharField(max_length=15)),
                ('view_read_only', models.BooleanField()),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_access_views_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_access_views_modified', to=settings.AUTH_USER_MODEL)),
                ('view_resp_id', models.ForeignKey(db_column='view_resp_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_RESPONSIBILITY')),
            ],
            options={
                'db_table': 'TM_ACCESS_VIEWS',
            },
        ),
    ]
