# Generated by Django 2.2.1 on 2019-08-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tm_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tm_responsibility',
            name='resp_dept_id',
            field=models.ForeignKey(db_column='resp_dept_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_DEPT'),
        ),
        migrations.AddField(
            model_name='tm_responsibility',
            name='resp_post_id',
            field=models.ForeignKey(db_column='resp_post_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_POST'),
        ),
        migrations.AddField(
            model_name='tm_responsibility',
            name='resp_user_group_id',
            field=models.ForeignKey(db_column='resp_user_group_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_USER_GROUP'),
        ),
        migrations.CreateModel(
            name='TM_DIV',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('div_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('div_name', models.CharField(max_length=15)),
                ('div_desc', models.CharField(max_length=30)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_div_created', to=settings.AUTH_USER_MODEL)),
                ('div_dept_id', models.ForeignKey(db_column='div_dept_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_DEPT')),
                ('div_org_id', models.ForeignKey(db_column='div_org_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_ORG')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_div_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TM_DIV',
            },
        ),
        migrations.AddField(
            model_name='tm_post',
            name='post_div_id',
            field=models.ForeignKey(db_column='post_div_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_DIV'),
        ),
        migrations.AddField(
            model_name='tm_responsibility',
            name='resp_div_id',
            field=models.ForeignKey(db_column='resp_div_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_DIV'),
        ),
        migrations.AddField(
            model_name='tm_user',
            name='user_div_id',
            field=models.ForeignKey(db_column='user_div_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_DIV'),
        ),
        migrations.AddField(
            model_name='tm_user_group',
            name='group_div_id',
            field=models.ForeignKey(db_column='group_div_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_DIV'),
        ),
    ]
