# Generated by Django 2.2.1 on 2019-08-09 06:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tm_users', '0003_auto_20190808_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tm_access_views',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 6, 51, 41, 911582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tm_dept',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 6, 51, 41, 911582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tm_div',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 6, 51, 41, 911582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tm_org',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 6, 51, 41, 911582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tm_org_contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 6, 51, 41, 911582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tm_post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 6, 51, 41, 911582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tm_responsibility',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 6, 51, 41, 911582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tm_user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 6, 51, 41, 911582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tm_user_contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 6, 51, 41, 911582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tm_user_group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 6, 51, 41, 911582, tzinfo=utc)),
        ),
    ]
