# Generated by Django 2.2.1 on 2019-08-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm_users', '0005_auto_20190809_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tm_org',
            name='modified_by',
        ),
    ]
