# Generated by Django 2.2.1 on 2019-08-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm_users', '0006_remove_tm_org_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tm_org',
            name='created_by',
        ),
    ]
