# Generated by Django 2.2.1 on 2019-08-11 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tm_users', '0007_remove_tm_org_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tm_org',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_org_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tm_org',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_org_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
