# Generated by Django 2.2.1 on 2019-08-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_users', '0008_auto_20190811_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='tm_access_views',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tm_access_views',
            name='status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tm_dept',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tm_dept',
            name='status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tm_div',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tm_div',
            name='status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tm_org',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tm_org',
            name='status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tm_org_contact',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tm_org_contact',
            name='status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tm_post',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tm_post',
            name='status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tm_responsibility',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tm_responsibility',
            name='status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tm_user',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tm_user',
            name='status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tm_user_contact',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tm_user_contact',
            name='status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tm_user_group',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tm_user_group',
            name='status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
