# Generated by Django 2.2.1 on 2019-08-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_users', '0009_auto_20190811_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tm_access_views',
            name='modified_by',
            field=models.CharField(default='dev.skapss@gmail.com', max_length=20),
        ),
        migrations.AlterField(
            model_name='tm_dept',
            name='modified_by',
            field=models.CharField(default='dev.skapss@gmail.com', max_length=20),
        ),
        migrations.AlterField(
            model_name='tm_div',
            name='modified_by',
            field=models.CharField(default='dev.skapss@gmail.com', max_length=20),
        ),
        migrations.AlterField(
            model_name='tm_org',
            name='modified_by',
            field=models.CharField(default='dev.skapss@gmail.com', max_length=20),
        ),
        migrations.AlterField(
            model_name='tm_org_contact',
            name='modified_by',
            field=models.CharField(default='dev.skapss@gmail.com', max_length=20),
        ),
        migrations.AlterField(
            model_name='tm_post',
            name='modified_by',
            field=models.CharField(default='dev.skapss@gmail.com', max_length=20),
        ),
        migrations.AlterField(
            model_name='tm_responsibility',
            name='modified_by',
            field=models.CharField(default='dev.skapss@gmail.com', max_length=20),
        ),
        migrations.AlterField(
            model_name='tm_user',
            name='modified_by',
            field=models.CharField(default='dev.skapss@gmail.com', max_length=20),
        ),
        migrations.AlterField(
            model_name='tm_user_contact',
            name='modified_by',
            field=models.CharField(default='dev.skapss@gmail.com', max_length=20),
        ),
        migrations.AlterField(
            model_name='tm_user_group',
            name='modified_by',
            field=models.CharField(default='dev.skapss@gmail.com', max_length=20),
        ),
    ]
