# Generated by Django 2.2.1 on 2019-08-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_users', '0011_auto_20190811_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tm_user',
            name='password',
        ),
        migrations.AlterField(
            model_name='tm_access_views',
            name='view_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tm_org_contact',
            name='org_cont_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tm_responsibility',
            name='resp_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tm_user_contact',
            name='user_cont_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
