# Generated by Django 2.2.1 on 2019-08-11 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tm_users', '0012_auto_20190811_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='TM_CITY',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('status_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(default='', max_length=20)),
                ('city_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=15)),
                ('city_code', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'TM_CITY',
            },
        ),
        migrations.CreateModel(
            name='TM_COUNTRY',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('status_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(default='', max_length=20)),
                ('country_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=15)),
                ('country_code', models.CharField(max_length=5)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_country_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TM_COUNTRY',
            },
        ),
        migrations.CreateModel(
            name='TM_ZIPCODE',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('status_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(default='', max_length=20)),
                ('zipcode_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('zipcode', models.CharField(max_length=5)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_zipcode_created', to=settings.AUTH_USER_MODEL)),
                ('zipcode_city_id', models.ForeignKey(db_column='state_country_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_CITY')),
            ],
            options={
                'db_table': 'TM_ZIPCODE',
            },
        ),
        migrations.CreateModel(
            name='TM_STATE',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('status_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(default='', max_length=20)),
                ('state_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=15)),
                ('state_code', models.CharField(max_length=5)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_state_created', to=settings.AUTH_USER_MODEL)),
                ('state_country_id', models.ForeignKey(db_column='state_country_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_COUNTRY')),
            ],
            options={
                'db_table': 'TM_STATE',
            },
        ),
        migrations.AddField(
            model_name='tm_city',
            name='city_state_id',
            field=models.ForeignKey(db_column='state_country_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_users.TM_STATE'),
        ),
        migrations.AddField(
            model_name='tm_city',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_city_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
